### ISSUE TITLE
Double click to edit - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by BigBoss320** [Farcrada/Double-click-to-edit#1]
This plug-in worked for a while, then it doesn't work anymore. When I double-click on the message, the window of "3 points" opens.
![2019-07-10 (3)](https://user-images.githubusercontent.com/44122706/60999560-bd03b900-a35b-11e9-978a-fe09fb49d125.png)

**Comment by pekatour** [comment]
+1

**Comment by Farcrada** [comment]
I've fixed this in the new update, uploading now.
