### ISSUE TITLE
An other bug with google option

### ISSUE THREAD

**Issue by BigBoss320** [Farcrada/Double-click-to-edit#10]
Hello I found an other bug. The plug-in doesn't work if google translation tool is disabled.
[DoubleClickToEdit.zip](https://github.com/Farcrada/Double-click-to-edit/files/3664619/DoubleClickToEdit.zip)

**Comment by Farcrada** [comment]
Correct, a null is returned because the other plugin is not present thus nothing happens. Working on it.

**Comment by Farcrada** [comment]
Fixed in: https://github.com/Farcrada/Double-click-to-edit/commit/5f6c0096788a1f61915f6862c12a66cc313a7fe8

Looping through now, previous errors with having both PersonalPins and Translate enabled should be fixed now too.
