### ISSUE TITLE
Double-Click-To-Edit no longer working on latest Discord

### ISSUE THREAD

**Issue by Insan1ty0ne** [Farcrada/Double-click-to-edit#11]
Release Channel: PTB
Build Number: 53762 
Version Hash: cf7e417a90ed9cde72a44cb17fe1a277da4c3b10
Issue Description: The plugin simply does not work after a recent update.

**Comment by Farcrada** [comment]
Thank you very much for the update. I suspect this will be coming to the stable release channels soon?

Originally this is made for just the stable installs, so I was stumped to find out it worked on my end. I love to see that the plugin has reached so far, so I'm installing PTB right now to attempt a fix.

**Comment by Insan1ty0ne** [comment]
> Thank you very much for the update. I suspect this will be coming to the stable release channels soon?
> 
> Originally this is made for just the stable installs, so I was stumped to find out it worked on my end. I love to see that the plugin has reached so far, so I'm installing PTB right now to attempt a fix.

I use this plugin all the time! It is great! It makes editing comments SO much easier and faster! As far as I know, features that make it to the PTB are going to be put into the Stable build. I used to use the Canary branch, but then I realized that some of the features that end up in the Canary branch never make it to PTB or Stable.

**Comment by Farcrada** [comment]
Good to hear!

So far, this seems like a complete redesign of how plugins are loaded. I can't get my plugin to initialize. In fact. I can't get any plugin to work on PTB. So I feel like this requires a BD update to start with. Which is unfortunate.

Either that or I'm missing something painfully obvious. Feel free to teach me the ways of the PTB.

**Comment by Farcrada** [comment]
Addendum: Might you be using a(nother) plugin that you can confirm is working?

**Comment by Insan1ty0ne** [comment]
> Addendum: Might you be using a(nother) plugin that you can confirm is working? If so, might I request the link?

This plug-in is confirmed working for me: https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/ServerFolders

**Comment by Farcrada** [comment]
Thank you, found the issue with it not loading. Working towards a fix.

**Comment by Farcrada** [comment]
Yes, new version uploaded. Seen as I didn't want to have unsuspected issues I figured a new file would be better. Though I'm thinking of merging anyway and then dividing on the user's system by detecting which Discord version is installed.

That being said, I hope it all works now.

**Comment by Farcrada** [comment]
If you've already downloaded the new one, I scuffed the version numbers so it won't update on its own. I suggest a re-download.

Sorry, my bad.

**Comment by Insan1ty0ne** [comment]
Thanks for the quick update! You are awesome! Now if only the other couple of plugins that I use ALL the time would get updated...

**Comment by Farcrada** [comment]
And as I wake up this morning I find that the standard Discord just updated to the original issue here. Also, how long have those other plugins been out of date?
