### ISSUE TITLE
Message popup menu remains open

### ISSUE THREAD

**Issue by edo9300** [Farcrada/Double-click-to-edit#12]
With the latest update, the plugin works, there's an issue tho, whenever you finish editing a message and confirm it, the message options menu pops up, and the same happens when you try to doble click on another person message, in that case, you wont' be able to edit it (obviously) but the menu will still pop up

**Comment by Farcrada** [comment]
Roger, working on it.

**Comment by vmurray1** [comment]
Likewise the context menu opens and stays open if you double click another one of your own messages while still in the edit menu. I.E you misclick the wrong message and then try to edit a different one.

**Comment by Farcrada** [comment]
I recognize the issue, however I've not been successful in finding a solution. I'm also trying to revamp the way the plugin works in the hopes preventing these types of random issues.

Thank you for your patience.

**Comment by Farcrada** [comment]
Yes, people! It took me a bit but the update should be rolling out to everyone! https://github.com/Farcrada/Double-click-to-edit/commit/5f7a0a5c91efab0097cf68dacdbaafce6c68e792

Thank you very much for your patience, the PTB version should follow soon!
