### ISSUE TITLE
Cannot edit consecutive messages

### ISSUE THREAD

**Issue by edo9300** [Farcrada/Double-click-to-edit#13]
The last commits fixed the issue with the menu staying open :), but now there's another bug, if you have multiple consecutive messages, you'll be able to edit only the first one, not the others

**Comment by Farcrada** [comment]
Roger. On it.

**Comment by Farcrada** [comment]
Got it fixed! https://github.com/Farcrada/Double-click-to-edit/commit/a01307bc0648561d73b24d0200af212f7e154b6b

Thanks for the heads up!
