### ISSUE TITLE
DoubleClickToEditPTB Not working because of corrupted update

### ISSUE THREAD

**Issue by Insan1ty0ne** [Farcrada/Double-click-to-edit#15]
Release Channel: PTB
Build Number: 54886
Version Hash: 61c56156e10854e22668a63110fd83290b117730
Issue Description: The plugin is no longer working as of this build of the Discord App.

**Comment by Farcrada** [comment]
There might've been an issue with the latest few updates I've made. I request you download the plugin again and see if it still doesn't work.

At this time the PTB version seems to work on the PTB version of Discord for me. Please let me know how it goes.

**Comment by Insan1ty0ne** [comment]
> There might've been an issue with the latest few updates I've made. I request you download the plugin again and see if it still doesn't work.
> 
> At this time the PTB version seems to work on the PTB version of Discord for me. Please let me know how it goes.

You were right, I went ahead and downloaded the plugin fresh from the repo and all is well. My apologies for the false issue!

**Comment by Farcrada** [comment]
Good to hear! I'll leave it open for future people.
