### ISSUE TITLE
Return if already editing message - prevents loss of edit when double clicking during edit (i.e for word selection)

### ISSUE THREAD

**Issue by cmd430** [Farcrada/Double-click-to-edit#16]
Simple fix is to check for the absence of the `da-zalgo` class and return, editing line 48 seems to work fine

https://github.com/Farcrada/Double-click-to-edit/blob/d2a0aa1e7fa812adcb1ff527680138fa495f59f2/DoubleClickToEditPTB.plugin.js#L48
becomes 
```javascript
if (!messagediv || !messagediv.classList.contains('da-zalgo'))
```

**Comment by Farcrada** [comment]
Damn. Good spot. Updating now.
