### ISSUE TITLE
Version 0.5.0

### ISSUE THREAD

**Issue by Clamier** [Farcrada/Double-click-to-edit#2]
Hello your new version dont work 
When I double-click on the message, the window of "3 points" opens.

i have the new version updated 18 hours ago.

**Comment by Farcrada** [comment]
That's very odd. However I do think that there's the possibility that Discord didn't pick up the new version. I recommend you delete the existing file from the plug-in folder restart Discord, and then paste it back.

Does that help?

**Comment by Farcrada** [comment]
Version 0.6.0 should have this fixed for all languages. My apologies.
