### ISSUE TITLE
Double click to edit - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by BigBoss320** [Farcrada/Double-click-to-edit#3]
Hello,
I still encounter the same bug.
[BugPluginMP4.zip](https://github.com/Farcrada/Double-click-to-edit/files/3387189/BugPluginMP4.zip)

I reinstalled Discord and BetterDiscord. Without success. This is the only plug-in enabled. It doesn't work anymore.

**Comment by Farcrada** [comment]
Thank you for the video it helped immensely with fixing. On it right now, merging with/duplicate of: https://github.com/Farcrada/Double-click-to-edit/issues/2
