### ISSUE TITLE
Stopped worked recently (fix included)

### ISSUE THREAD

**Issue by SickBoySB** [Farcrada/Double-click-to-edit#4]
Plugin has ceased working in recent versions. Fix is to replace all instances of "rii.memoizedProps.children[3]" with "rii.memoizedProps.children[1]"

**Comment by Farcrada** [comment]
Thanks, wonder why Discord keeps changing this, glad I implemented the updater.

Resolved in: https://github.com/Farcrada/Double-click-to-edit/commit/e6c11ab01cfe1957da211869ef32a693dc31a47e
