### ISSUE TITLE
New update of discord

### ISSUE THREAD

**Issue by Clamier** [Farcrada/Double-click-to-edit#6]
**Describe the bug**
New update of discord
it broke all scripts and themes so i understand this dont work too i just wanted to let you know in advance.

**Please complete the following information:**
 - OS: [Windows 7 64 Bit Ultimate]
 - Plugin version [0.6.1]
 - (BD) Version  0.3.2]
 - (BBD) Version  0.2.17]

**Additional context**
Dont work at all nothing happen.

**Comment by Farcrada** [comment]
On it, thanks for the heads-up.

**Comment by Farcrada** [comment]
As it stands I'm gonna have to wait for better discord to update itself (considering you mentioned other projects failing too) before I'll attempt fixing it. Because I feel like some of the properties I'm using will get looked at also.

To re-iterate: On hold for now.

**Comment by Farcrada** [comment]
After careful dissection, I have found a fix! Uploading now!

**Comment by Farcrada** [comment]
https://github.com/Farcrada/Double-click-to-edit/commit/6195058ac4d37825730ac492f12325a419d463d8 New update is uploaded, let me know how it fares.
