### ISSUE TITLE
Double click to edit - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by master3395** [Farcrada/Double-click-to-edit#7]
Double-clicking does not respond.

**Comment by master3395** [comment]
![image](https://user-images.githubusercontent.com/4199669/65283699-fb75db00-db37-11e9-828e-4cba4b7c6051.png)

**Comment by Farcrada** [comment]
Have you updated to the latest update? I released 0.7.0 last Wednesday night. That should've fixed the issue for the last Discord update.

**Comment by master3395** [comment]
Seems like it was disabled when i updated it.
Your right, it works now.
