### ISSUE TITLE
Double Click to "Note"

### ISSUE THREAD

**Issue by NightWolf1038** [Farcrada/Double-click-to-edit#9]
Hi!
You're doing a great job with this plugin. I saw your last update about GoogleTranslate plugin.
There's this plugin (PersonalPins) that creates a menu item as you can see [here](https://puu.sh/EjK5y/ee12424462.png)
Here's a fix:
```
if(BdApi.getPlugin("PersonalPins"))
			if(BdApi.getPlugin("PersonalPins").started)
				editIndex = 2;
```

Thank you for your work! And sorry for my english, I'm in my phone.

**Comment by Farcrada** [comment]
Thanks for letting me know! Updated and pushed: https://github.com/Farcrada/Double-click-to-edit/commit/e0ba9583f9544c5eaafa2a6b134f99ef048c6a2f
